# docker-compose.yml

version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/redilab"  

  mongo:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data:

networks:
  backend:
